// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgAH97QVA2KzlUzX5N4OaBr_qkl6IRUs',
    appId: '1:376439119060:web:93dbd19e82313e952baf41',
    messagingSenderId: '376439119060',
    projectId: 'the-banana-tree-communit-6834e',
    authDomain: 'the-banana-tree-communit-6834e.firebaseapp.com',
    storageBucket: 'the-banana-tree-communit-6834e.firebasestorage.app',
    measurementId: 'G-1QE1T91PFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIL2YQDdSuw-kI_yFUTR9XsNADdDrMYx0',
    appId: '1:376439119060:android:7ce6a6def6e372eb2baf41',
    messagingSenderId: '376439119060',
    projectId: 'the-banana-tree-communit-6834e',
    storageBucket: 'the-banana-tree-communit-6834e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS7VVnHNqPQYIZjwz6CHhmzR24NvTUOR8',
    appId: '1:376439119060:ios:de4f0e6a2a1b56262baf41',
    messagingSenderId: '376439119060',
    projectId: 'the-banana-tree-communit-6834e',
    storageBucket: 'the-banana-tree-communit-6834e.firebasestorage.app',
    iosBundleId: 'com.example.theBananaTreeCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS7VVnHNqPQYIZjwz6CHhmzR24NvTUOR8',
    appId: '1:376439119060:ios:de4f0e6a2a1b56262baf41',
    messagingSenderId: '376439119060',
    projectId: 'the-banana-tree-communit-6834e',
    storageBucket: 'the-banana-tree-communit-6834e.firebasestorage.app',
    iosBundleId: 'com.example.theBananaTreeCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZgAH97QVA2KzlUzX5N4OaBr_qkl6IRUs',
    appId: '1:376439119060:web:a20dd678bb9780402baf41',
    messagingSenderId: '376439119060',
    projectId: 'the-banana-tree-communit-6834e',
    authDomain: 'the-banana-tree-communit-6834e.firebaseapp.com',
    storageBucket: 'the-banana-tree-communit-6834e.firebasestorage.app',
    measurementId: 'G-XER6K07Y4H',
  );

}